# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2020-10-26 15:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IncomingApply',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('incoming_doc_mark', models.CharField(max_length=16, null=True)),
                ('stock_mark', models.CharField(max_length=16, null=True)),
                ('apply_cons_mark', models.CharField(db_index=True, max_length=16)),
                ('asset_name', models.CharField(max_length=64, null=True)),
                ('proj_from', models.CharField(max_length=16, null=True)),
                ('proj_mark', models.CharField(max_length=64, null=True)),
                ('proj_name', models.CharField(max_length=64, null=True)),
                ('ini_from', models.CharField(max_length=64, null=True)),
                ('mat_mark', models.CharField(max_length=16)),
                ('mat_extend_mark', models.CharField(max_length=16, null=True)),
                ('mat_from', models.CharField(max_length=64, null=True)),
                ('pars', models.CharField(max_length=32)),
                ('mat_type', models.CharField(max_length=32)),
                ('dp', models.DateField(null=True)),
                ('supplyer', models.CharField(max_length=32, null=True)),
                ('bp', models.CharField(max_length=32, null=True)),
                ('use_date', models.DateField()),
                ('remove_date', models.DateField()),
                ('pms_status', models.CharField(max_length=32, null=True)),
                ('test_result', models.CharField(max_length=16)),
                ('wh_mark', models.CharField(max_length=16)),
                ('num', models.DecimalField(decimal_places=3, max_digits=12)),
                ('is_visible', models.BooleanField(default=False)),
                ('is_enable', models.BooleanField(default=False)),
                ('is_approve_reason', models.CharField(max_length=32)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.User')),
            ],
        ),
        migrations.CreateModel(
            name='IncomingIds',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('incoming_id', models.IntegerField(default=1)),
                ('stock_id', models.IntegerField(default=1)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
