# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2020-10-26 15:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incoming', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incomingapply',
            name='is_approve_reason',
            field=models.CharField(max_length=32, null=True),
        ),
    ]
