# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2020-10-26 16:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incoming', '0002_auto_20201026_1554'),
    ]

    operations = [
        migrations.AddField(
            model_name='incomingapply',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True),
            preserve_default=False,
        ),
    ]
