# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2020-10-28 15:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incoming', '0003_incomingapply_create_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='incomingapply',
            name='accessory',
            field=models.FileField(default=1, upload_to='incoming/'),
            preserve_default=False,
        ),
    ]
