# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2020-10-29 16:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('incoming', '0005_auto_20201029_1028'),
    ]

    operations = [
        migrations.CreateModel(
            name='Accessory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accessory', models.FileField(null=True, upload_to='%Y/%m%d')),
            ],
            options={
                'db_table': 'Accessory',
            },
        ),
        migrations.RemoveField(
            model_name='incomingapply',
            name='accessory',
        ),
        migrations.AddField(
            model_name='accessory',
            name='table_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='incoming.IncomingApply'),
        ),
    ]
