# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2020-10-11 18:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Errlog',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('path', models.CharField(max_length=128, null=True)),
                ('error', models.CharField(max_length=256)),
                ('err_time', models.DateTimeField(null=True)),
                ('is_visible', models.BooleanField(default=True)),
                ('is_enable', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='user.User')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Loginlog',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('login_ip', models.CharField(max_length=32)),
                ('login_time', models.DateTimeField()),
                ('is_visible', models.BooleanField(default=True)),
                ('is_enable', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='user.User')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Syslog',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('moudle_name', models.CharField(max_length=16, null=True)),
                ('action', models.CharField(max_length=16)),
                ('do_time', models.DateTimeField()),
                ('is_visible', models.BooleanField(default=True)),
                ('is_enable', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='user.User')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
