# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2020-10-12 11:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Constructor',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cons_mark', models.CharField(db_index=True, max_length=16)),
                ('cons_name', models.CharField(max_length=32)),
                ('is_visible', models.BooleanField(default=True)),
                ('is_enable', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('mat_mark', models.CharField(db_index=True, max_length=16)),
                ('exp_mark', models.SmallIntegerField(db_index=True, default=0)),
                ('mat_type', models.CharField(max_length=32)),
                ('mat_des', models.CharField(max_length=256, null=True)),
                ('exp_class', models.CharField(max_length=256, null=True)),
                ('unit', models.CharField(max_length=8)),
                ('min_num', models.FloatField(default=1)),
                ('is_visible', models.BooleanField(default=True)),
                ('is_enable', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cons_mark', models.CharField(db_index=True, max_length=16, null=True)),
                ('wh_mark', models.CharField(db_index=True, max_length=16, null=True)),
                ('wh_name', models.CharField(max_length=32)),
                ('is_visible', models.BooleanField(default=True)),
                ('is_enable', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
