# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2020-10-13 16:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='constructor',
            name='manager',
            field=models.CharField(max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='constructor',
            name='tel',
            field=models.CharField(max_length=32, null=True),
        ),
    ]
