# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2020-10-14 10:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0002_auto_20201013_1619'),
    ]

    operations = [
        migrations.RenameField(
            model_name='constructor',
            old_name='manager',
            new_name='con_manager',
        ),
        migrations.RenameField(
            model_name='constructor',
            old_name='tel',
            new_name='con_tel',
        ),
        migrations.AddField(
            model_name='warehouse',
            name='wh_manager',
            field=models.CharField(max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='warehouse',
            name='wh_tel',
            field=models.CharField(max_length=32, null=True),
        ),
    ]
