# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2020-10-14 10:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0003_auto_20201014_1033'),
    ]

    operations = [
        migrations.RenameField(
            model_name='constructor',
            old_name='con_manager',
            new_name='cons_manager',
        ),
        migrations.RenameField(
            model_name='constructor',
            old_name='con_tel',
            new_name='cons_tel',
        ),
    ]
