# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2020-10-14 13:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0004_auto_20201014_1035'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='material',
            name='exp_class',
        ),
        migrations.RemoveField(
            model_name='material',
            name='exp_mark',
        ),
        migrations.AddField(
            model_name='material',
            name='is_device',
            field=models.BooleanField(default=True),
        ),
    ]
