# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2020-10-11 18:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('group_name', models.CharField(max_length=16, null=True)),
                ('permission_moudle', models.CharField(default='["*",]', max_length=512)),
                ('permission_account', models.CharField(default='["*",]', max_length=512)),
                ('permission_edit_master', models.BooleanField(default=True)),
                ('is_visible', models.BooleanField(default=True)),
                ('is_enable', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Moudle',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('class_big', models.CharField(max_length=16)),
                ('class_small', models.CharField(max_length=16)),
                ('name', models.CharField(max_length=16)),
                ('url', models.CharField(max_length=64)),
                ('state', models.SmallIntegerField(default=1)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user_name', models.CharField(db_index=True, max_length=16)),
                ('real_name', models.CharField(max_length=16)),
                ('department', models.CharField(max_length=32, null=True)),
                ('tel', models.CharField(max_length=32, null=True)),
                ('password', models.CharField(max_length=32)),
                ('is_visible', models.BooleanField(default=True)),
                ('is_enable', models.BooleanField(default=True)),
                ('group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='user.Group')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
